project:
  type: book
  output-dir: docs
  preview:
    port: 7772
    browser: true
  render:
    - "!to_do.qmd"

lang: ko-KR

book:
  title: "챗GPT SQL"
  subtitle: "범용 데이터 과학 도구"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd

    - part: "시작을 위한 준비"
      chapters:    
        - intro.qmd      
        - theory.qmd      
        - setup.qmd
        
    - part: "SQL 쿼리"
      chapters:
        - select.qmd
        - sort-filter.qmd
        - null-hygene.qmd
        - calc-agg.qmd
        - join.qmd
        - create.qmd
        - prog.qmd        

    - part: "현장활용법"
      chapters:
        - spreadsheet.qmd
        - etl.qmd
        - duck_postgreSQL.qmd
        - case_dvd.qmd
        
    - part: "챗GPT SQL"
      chapters:
        - text2sql.qmd
        - llm.qmd

        
    - references.qmd

format:
  html:
    theme: cosmo
    cover-image: images/logo.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap

bibliography: references.bib
link-citations: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: code-overflow
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console

editor: 
  markdown: 
    wrap: 72
    