
project:
  type: book
  output-dir: docs
  preview:
    port: 7771
    browser: false

lang: ko-KR

book:
  title: "챗GPT 데이터베이스"
  subtitle: "범용 데이터 과학 도구"
  author:
    - name: "이광춘"
      affiliations: "비영리법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd
    - intro.qmd
    - part: "환경설정"
      chapters:
        - 01-setup.qmd
        - 02-database.qmd        

    - part: "SQL"
      chapters:
        - 11-select.qmd
        - 12-sort-dup.qmd
        - 13-filter.qmd
        - 14-calc.qmd
        - 15-null.qmd
        - 16-agg.qmd
        - 17-join.qmd
        - 18-create.qmd
        - 19-prog.qmd

    - part: "챗GPT SQL"
      chapters:
        - 21-application.qmd

    - references.qmd














format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap

bibliography: references.bib
link-citations: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console
