project:
  type: book
  output-dir: docs
  preview:
    port: 7771
    browser: true

lang: ko-KR

book:
  title: "챗GPT SQL"
  subtitle: "범용 데이터 과학 도구"
  author:
    - name: "이광춘"
      affiliations: "비영리법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd
    - intro.qmd
    - part: "SQL"
      chapters:
        - setup.qmd
        - select.qmd
        - sort-dup.qmd
        - filter.qmd
        - calc.qmd
        - null.qmd
        - agg.qmd
        - join.qmd
        - hygene.qmd        
        - create.qmd
        - prog.qmd
        - prog-r.qmd
        
    - part: "활용사례"
      chapters:
        - spreadsheet.qmd
        - etl.qmd        

    - part: "챗GPT SQL"
      chapters:
        - application.qmd

    - references.qmd

format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap

bibliography: references.bib
link-citations: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console
