project:
  type: book
  output-dir: docs
  preview:
    port: 7771
    browser: true

lang: ko-KR

book:
  title: "챗GPT SQL"
  subtitle: "범용 데이터 과학 도구"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd

    - part: "들어가며"
      chapters:    
        - intro.qmd      
        - theory.qmd      
        - setup.qmd
        
    - part: "SQL 쿼리"
      chapters:
        - select.qmd
        - sort-filter.qmd
        # - sort-dup.qmd
        # - filter.qmd
        - null-hygene.qmd
        # - hygene.qmd        
        # - null.qmd
        - calc-agg.qmd
        # - calc.qmd
        # - agg.qmd
        - join.qmd
        - create.qmd
        - prog.qmd        
        # - prog-py.qmd
        # - prog-r.qmd
        
    - part: "활용사례"
      chapters:
        - spreadsheet.qmd
        - etl.qmd        
        - case_dvd.qmd
        
    - part: "챗GPT SQL"
      chapters:
        - advanced_db.qmd
        - llm.qmd

        
    - references.qmd

format:
  html:
    theme: cosmo
    cover-image: images/logo.png
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap

bibliography: references.bib
link-citations: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console
