project:
  type: book
  output-dir: docs
  preview:
    port: 7772
    browser: true
  render:
    - "!to_do.qmd"

lang: ko-KR

book:
  title: "챗GPT SQL"
  reader-mode: true
  subtitle: "SQL을 넘어 챗GPT와 떠나는 데이터 과학 여정"

  page-footer:
    left: |
      챗GPT SQL 책은 소프트웨어 카펜트리 Database and SQL 번역한 것이 포함되어 있습니다.
    right: |
      순수하게 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.

  cover-image: images/book_cover.jpg
  favicon: images/logo.png
  site-url: https://r2bit.com/gpt-sql/
  repo-url: https://github.com/bit2r/gpt-sql/
  repo-branch: main
  repo-actions: [edit, issue]
  

  google-analytics: "UA-229551680-1"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd

    - part: "시작을 위한 준비"
      chapters:    
        - intro.qmd      
        - theory.qmd      
        - setup.qmd
        
    - part: "SQL 쿼리"
      chapters:
        - select.qmd       # O
        - sort-filter.qmd  # O
        - null-hygene.qmd  # O
        - calc-agg.qmd     # X
        - join.qmd         # X
        - create.qmd       # X
        - prog.qmd         # X

    - part: "현장활용법"
      chapters:
        - spreadsheet.qmd # X
        - etl.qmd         # X
        - duck_postgreSQL.qmd # X
        - case_dvd.qmd    # X
        
    - part: "챗GPT SQL"
      chapters:
        - text2sql.qmd   # X
        - llm.qmd        # X

    - references.qmd     # X

format:
  html:
    theme: 
      - cosmo
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap
    code-link: true

    author-meta: "이광춘"
    include-in-header: "plausible.html"
    callout-appearance: simple      

bibliography: references.bib
link-citations: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: code-overflow
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console

editor: 
  markdown: 
    wrap: 72
    