
# 챗GPT SQL

[공익법인 한국 R 사용자회](https://r2bit.com/)에서 출판한 "챗GP SQL" 웹사이트로 오신 것을 환영합니다. 
이 책은 본격적으로 부상한 인공지능(AI) 기술인 챗GPT와 함께 SQL을 다양한 각도에서 다루고 있습니다.
챗GPT로 대표되는 생성형 AI 기술의 가장 큰 문제점 중 하나는 환각(허구, hallucination)의 가능성이다.
환각을 내포한 SQL 쿼리 생성문제를 확인하기 위해서 현재 기준 기여자가 87명의 집단지성으로 제작되고 현재도 꾸준히 업데이트되고 있는 소프트웨어 카펜트리 [데이터베이스와 SQL(Databases and SQL)](https://swcarpentry.github.io/sql-novice-survey/) 콘텐츠를 한글로 번역하고 생성형 AI가 생성한 SQL 쿼리를 검증하는 과정을 포함했다.

이 책은 SQL 쿼리를 여러분이 직접 작성하고 빠른 시간내에 체화할 수 있도록 복잡하고 어려운 내용을 최대한 단순하게 풀어서 설명하고 불필요하다고 생각되는 내용은 최대한 배제했다. 하지만, 다양한 상황에서 효과적인 SQL 쿼리를 작성하는데 필요한 다양한 개념들 예를 들어, OLTP/OLAP 데이터베이스, ETL/ELT, 프로그래밍 언어와 결합, 스프레드시트(엑셀) 등도 코드와 함께 넣어 실무에서도 바로 사용할 수 있도록 했다.  

데이터베이스와 SQL에 대해 어느 정도 기본적인 지식이 있는 독자는 쿼리작성의 기본기를 다루는 "SQL 쿼리"를 생략하고 바로 현장활용법과 챗GPT SQL로 넘어가는 것을 추천한다. 이 책을 통해서 SQL 쿼리 작성 기본기, 연관 데이터베이스 지식, 엑셀과 관계, ETL 과정을 통해 정형 파일(CSV 등) 데이터베이스로 담기는 과정, DuckDB, 데이터베이스 프로그래밍, OpenAI API 프로그래밍, 오픈소스 LLM 모델을 활용한 챗GPT SQL을 배울 수 있다. 

"챗GPT와 SQL"은 [기여자 행동 강령](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html)을 준용한다는 점에 유의하고, 이 책에 기여하는 것은 여러분은 해당 조항을 준수하는 데 동의함을 의미한다.

## 감사의 글 {.unnumbered}

이 책이 탄생할 수 있도록 도움을 주신 여러분께 깊은 감사의 마음을 표합니다.

기술적인 부분에서 깊은 통찰력을 제공해주신 한국 R 사용자회 유충현 회장님, 챗GPT가 국내에 소개된 후 가장 먼저 챗GPT를 세밀하게 조명할 수 있도록 교육 기회를 주신 경기도의회 문승호, 이자형, 장한별 의원님, 광명시 박승원 시장님, 김종업 센터장님, 김포시 김규식 부시장님, 지방행정연구원 최인수, 전대욱, 김필, 주희진  박사님, 경기도청 AI빅데이터 산업과 이수재 과장님, 원금동, 최정환, 윤여찬 팀장님, 나이스 디앤알 박정우 대표님, 남영민 본부장님, 서울교육청 조희연 교육감님, 양신호 원장님, 김선자 장학관님, 디플래닉스 김범진 전대표님, 장석호 대표님, 이용빈님, 경기도 경제과학진흥원 임문영 상임이사님, 건국대 미래지식교육원 이영범 원장님, 세종대 곽창규, 김현정 교수님께 감사드립니다.

이 책의 공개와 출판이 가능했던 것은 한국 R 사용자회의 지원 덕분입니다. 행정사법인 광화문 최순영 대표님, 한채민 과장님, 법무법인 평안 김형주 변호사님, 법률사무소 하우림 정병운 변호사님, 홍성학 감사님, 김호성님, 김현철님, 형환희님, 명지대 박순만 교수님, Macao Polytechnic University 김송규 교수님, 한국텍학회 김강수님, 배달의 민족 이봉호님, 홍익대 이현진 교수님, 경상국립대 백원희 교수님, 세종과학예술영재학교 김종헌 선생님께 진심으로 감사드립니다. 

한국 R 사용자회 활동에서 소프트웨어 카펜트리의 영향은 결코 무시할 수 없습니다. 소프트웨어 카펜트리를 설립한 Greg Wilson 박사님, 카펜트리 재단의 Kari Jordan 박사님, AsiaR 커뮤니티를 이끌고 계신 Janani Ravi 박사님, 서울 R 미트업에서 발표해주신 제빈 웨스트 교수님, 그리고 곽수영, 장연훈, 나성호, 안영찬, 박남호, 공병규, 김용우님께 감사의 말씀을 드립니다.

지적 자극을 주시고 더 넓은 세상을 보게 해주신 국가교육위원회 이배용 위원장님, 정대화 상임위원님, 김수환 전문위원님, 삼정 KPMG 장지수 부대표님, 박문구 전무님, 가톨릭 의대 문건웅 교수님, 성균관대 최재성 교수님, 국무조정실 장명헌 사무관님, 제주대 안도현 교수님, 명지대 박순만 교수님, 엘릭스 이희정 전대표님, 서울대 고길곤 교수님, 한밭대 이원일 교수님에게 깊은 감사의 말씀을 전합니다.

공공정책분야의 빅데이터 분석 활성화를 격려해주신 노웅래 의원님, 김병욱 의원님, 성남시의회 조정식 의원님, 환경보전협회 남광우 전 상근부회장님, 공공의창 최정묵 박사님, 조원씨앤아이 김대진 대표님, 
그리고 이 책 출판에 관심이 많으신 오마이뉴스의 김지현 기자님, 나눔국민운동본부 위정희 이사님에게 감사의 인사를 전합니다.

이 책이 출간되는데 있어 이들 모든 분들의 도움 없이는 어려웠을 것입니다. 그동안의 관심과 지원에 깊은 감사를 드리며, 이 책이 데이터 과학의 발전과 독자들에게 도움이 될 수 있기를 바라는 마음으로 마무리하겠습니다.



